// com
export const ADD_COM = 'ADD_COM'
export const DELETE_COM = 'DELETE_COM'
export const UPDATE_COM = 'UPDATE_COM'
export const FOCUS_COM = 'FOCUS_COM'

// layer
export const UPDATE_COM_ZINDEX = 'UPDATE_COM_ZINDEX'

// page
export const ADD_PAGE = 'ADD_PAGE'
export const DELETE_PAGE = 'DELETE_PAGE'
export const UPDATE_PAGE_ORDER = 'UPDATE_PAGE_ORDER'
export const FOCUS_PAGE = 'FOCUS_PAGE'
export const UPDATE_PAGE_SETTINGS = 'UPDATE_PAGE_SETTINGS'

// template
export const FETCH_TEMPLATELIST_BEGIN = 'FETCH_TEMPLATELIST_BEGIN'
export const FETCH_TEMPLATELIST_SUCCESS = 'FETCH_TEMPLATELIST_SUCCESS'
export const FETCH_TEMPLATELIST_FAILURE = 'FETCH_TEMPLATELIST_FAILURE'
export const SAVE_TEMPLATELIST_BEGIN = 'FETCH_TEMPLATELIST_BEGIN'
export const SAVE_TEMPLATELIST_SUCCESS = 'FETCH_TEMPLATELIST_SUCCESS'
export const SAVE_TEMPLATELIST_FAILURE = 'SAVE_TEMPLATELIST_FAILURE'
export const APPLY_TEMPLATE = 'APPLY_TEMPLATE'

// work
export const FETCH_WORKS_BEGIN = 'FETCH_WORKS_BEGIN'
export const FETCH_WORKS_SUCCESS = 'FETCH_WORKS_SUCCESS'
export const FETCH_WORKS_FAILURE = 'FETCH_WORKS_FAILURE'
export const SAVE_WORK_BEGIN = 'SAVE_WORK_BEGIN'
export const SAVE_WORK_SUCCESS = 'SAVE_WORK_SUCCESS'
export const SAVE_WORK_FAILURE = 'SAVE_WORK_FAILURE'
export const APPLY_WORK = 'APPLY_WORK'

// main
export const UNDO = 'UNDO'
export const REDO = 'REDO'

// setting
export const VISIBLE = 'VISIBLE'