export const ADD_COM = 'ADD_COM'
export const DELETE_COM = 'DELETE_COM'
export const UPDATE_COM = 'UPDATE_COM'
export const FOCUS_COM = 'FOCUS_COM'

export const FETCH_TEMPLATELIST_BEGIN = 'FETCH_TEMPLATELIST_BEGIN'
export const FETCH_TEMPLATELIST_SUCCESS = 'FETCH_TEMPLATELIST_SUCCESS'
export const FETCH_TEMPLATELIST_FAILURE = 'FETCH_TEMPLATELIST_FAILURE'
