export const ADD_COM = 'ADD_COM';
export const DELETE_COM = 'DELETE_COM';
export const UPDATE_COM = 'UPDATE_COM';
export const FOCUS_COM = 'FOCUS_COM';

// page
export const ADD_PAGE = 'ADD_PAGE';
export const DELETE_PAGE = 'DELETE_PAGE';
export const FOCUS_PAGE = 'FOCUS_PAGE';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const EXCHANGE_COM_ORDER = 'EXCHANGE_COM_ORDER';
export const SET_PAGE_SETTINGS = 'SET_PAGE_SETTINGS';
export const SET_PAGE_STYLES = 'SET_PAGE_STYLES';

// template
export const FETCH_TEMPLATELIST_BEGIN = 'FETCH_TEMPLATELIST_BEGIN';
export const FETCH_TEMPLATELIST_SUCCESS = 'FETCH_TEMPLATELIST_SUCCESS';
export const FETCH_TEMPLATELIST_FAILURE = 'FETCH_TEMPLATELIST_FAILURE';
export const SAVE_TEMPLATELIST_BEGIN = 'FETCH_TEMPLATELIST_BEGIN';
export const SAVE_TEMPLATELIST_SUCCESS = 'FETCH_TEMPLATELIST_SUCCESS';
export const SAVE_TEMPLATELIST_FAILURE = 'SAVE_TEMPLATELIST_FAILURE';
export const APPLY_TEMPLATE = 'APPLY_TEMPLATE';

// work
export const FETCH_WORKS_BEGIN = 'FETCH_WORKS_BEGIN';
export const FETCH_WORKS_SUCCESS = 'FETCH_WORKS_SUCCESS';
export const FETCH_WORKS_FAILURE = 'FETCH_WORKS_FAILURE';
export const SAVE_WORK_BEGIN = 'SAVE_WORK_BEGIN';
export const SAVE_WORK_SUCCESS = 'SAVE_WORK_SUCCESS';
export const SAVE_WORK_FAILURE = 'SAVE_WORK_FAILURE';
export const APPLY_WORK = 'APPLY_WORK';
export const CREATE_WORK = 'CREATE_WORK';

// settings
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

// main
export const UNDO = 'UNDO';
export const REDO = 'REDO';

// status
export const SET_CURRENT_COM_ID = 'SET_CURRENT_COM_ID';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_MATERIAL_DIALOG_STATUS = 'SET_MATERIAL_DIALOG_STATUS';
export const SET_PAGE_SETTINGS_DIALOG_STATUS =
  'SET_PAGE_SETTINGS_DIALOG_STATUS';
export const SET_MATERIAL_CURRENT_VALUE = 'SET_MATERIAL_CURRENT_VALUE';
export const SET_MATERIAL_CHOOSEN_COM = 'SET_MATERIAL_CHOOSEN_COM';
export const SET_BASIC_DIALOG_STATUS = 'SET_BASIC_DIALOG_STATUS';
export const SET_LATEST_WORK_ID = 'SET_LATEST_WORK_ID';

// auth
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const DELETE_AUTH = 'DELETE_AUTH';
export const SET_WECHAT_SHARE_URL = 'SET_WECHAT_SHARE_URL';
